### ISSUE TITLE
Huge slug size

### ISSUE THREAD

**Issue by j4mie** [heroku/heroku-geo-buildpack#6]
Following [this](https://help.heroku.com/D5INLB1A/python-s-build_with_geo_libraries-legacy-feature-is-now-deprecated) announcement we switched a Django app over from using the old way to using this buildpack.

Before, the slug size was 200.2MB. After, it was 312.2MB, which exceeds Heroku's soft slug size limit.

Looking on a one-off dyno:

```
$ du -hs .heroku-geo-buildpack/
714M    .heroku-geo-buildpack/
```

This seems pretty huge! Is there anything that can be done to improve this?

Thanks :)

**Comment by codingjoe** [comment]
I noticed the same thing. This was fixed by @syphar in the Python buildpack a long time ago, see https://github.com/heroku/heroku-buildpack-python/commit/c44ab4cd03e3d14aa4d775ff6621ea806120362a

The current build includes static binaries, which are not needed by Python.
IMHO they should be dropped again, as they were in the Python buildpack to allow people to transition smoothly.

cc @KevinBrolly

**Comment by filwaitman** [comment]
Same here. `du` inside the dynos:

```
heroku run "du -hs .[^.]* * | sort -hr | head -n 10" -a XXXX

714M	.heroku-geo-buildpack
437M	.heroku
10M         < sum of all my project stuff >
```

**Comment by KevinBrolly** [comment]
I merged the PR + compiled and uploaded the new binaries. You may need to purge your cache once again to get them. Thanks @codingjoe @j4mie and @filwaitman

**Comment by codingjoe** [comment]
Well it's better now, but there are still a lot of build files, that do not need to be there. I'll try to make some time to clean those up.

**Comment by filwaitman** [comment]
@KevinBrolly thanks for that!

I tried to purge cache and redeploy... and got the same slug size after all. Any clues about what is happening?

**Comment by codingjoe** [comment]
I browsed a bit though the dyno files and there is still stuff there that isn't needed. I will try to look into this, but I wanted to add some more tests first, to make sure not to break anything.

**Comment by codingjoe** [comment]
```
root@683dec410d22:/tmp/tmp.1AxmfFUUvh# du -hd1  
110M    ./include
7.3M    ./share
2.4M    ./bin
140M    ./lib
359M    .
```

So I spend some time checking, there are still tons files that are not needed for Python. Actually Python should be fine with only the `lib` directory.

@KevinBrolly do we need the other binaries for anything else? I am fairly certain we can drop `includes` since it only contains boost with is only needed to compile the static Python bindings. It's not needed during runtime.

To be fair though, the `include`s are highly compressible. The static bindings are of course not. Dropping everything, but the bindings will only share ~10 MB of the slug size in the case of GDAL. Still, this could make a sizable difference in dyno startup times.

**Comment by KevinBrolly** [comment]
@codingjoe With the great changes from #8 and #11 we have gone from:

> Before, the slug size was 200.2MB. After, it was 312.2MB, which exceeds Heroku's soft slug size limit.
> 
> Looking on a one-off dyno:
> 
> ```
> $ du -hs .heroku-geo-buildpack/
> 714M    .heroku-geo-buildpack/
> ```

Down to:

`
$ du -hs .heroku-geo-buildpack/
141M	.heroku-geo-buildpack/
`

The bulk of the size is the `include`s but as you noted these are highly compressible and the buildpack itself only adds around 18 MB to the slug size:

`
$ du -hs slug.tgz
18M	slug.tgz
`

I think shrinking it any more would make a pretty negligible difference to startup times. But if we can easily take more size away I am all for it. We could drop `include`s with the only downside I can think of being that it is not available for subsequent buildpacks. We do currently add them to `C_INCLUDE_PATH` [here](https://github.com/heroku/heroku-geo-buildpack/blob/master/bin/compile#L69) so this could cause problems if someone else relies on this.
